Improved calling comparison Makefile; PaperSimulations Makefile stable
calling-comparison.mk:
- always run with ref and without ref
- store result in k31/ directory so we can run with diff kmer size
- thread reference through the pop graph (-> .ctp)
- when only one haploid don't do noref -- wouldn't make sense, only one chr so no variants
- don't do oldbc or shaded when NUM_INDIVS > 1 -- memory too high

diff --git a/test/benchmark/paperSimulations/Makefile b/test/benchmark/paperSimulations/Makefile
--- a/test/benchmark/paperSimulations/Makefile
+++ b/test/benchmark/paperSimulations/Makefile
@@ -1,79 +1,91 @@
+# Makefile to run simulation for paper
+
 HGCHR1=http://hgdownload.cse.ucsc.edu/goldenPath/hg19/chromosomes/chr1.fa.gz
 STAPH=http://www.ebi.ac.uk/Tools/dbfetch/dbfetch?db=embl&id=FN433596&format=fasta&style=raw
 FACAT=../../../libs/seq_file/bin/facat
 
 # PhiX.1.fq.gz needs to be downloaded
-PROFILE_READS=PhiX.1.fq.gz
+PROFILE_READS=../PhiX.1.fq.gz
 
-# Set stampy to the command needed
-STAMPY_BIN=~/bioinf/stampy-1.0.20/stampy.py
+NAMES=HsOneErrorReads100 StaphOneErrorReads100 \
+			HsOneErrorReads250 StaphOneErrorReads250 \
+			HsOneNoErrorReads100 StaphOneNoErrorReads100 \
+			HsOneNoErrorReads250 StaphOneNoErrorReads250 \
+			HsManyErrorReads100 StaphManyErrorReads100 \
+			HsManyErrorReads250 StaphManyErrorReads250
 
-UNAME=$(shell uname -s)
-ifeq ($(UNAME),Darwin)
-	STAMPY=python2.6 $(STAMPY_BIN)
-else
-	STAMPY=python $(STAMPY_BIN)
-endif
+PROJ=$(addprefix proj, $(NAMES))
 
-all: chr1/chr1.fa.gz staph/staph.fa.gz run-files $(PROFILE_READS)
+REFS=chr1/chr1.fa.gz chr1/chr1.fa chr1/chr1.fa.fai \
+     staph/staph.fa.gz staph/staph.fa staph/staph.fa.fai
+
+# Number of events
+HsOneSNPs=225000
+HsOneIndels=25000
+HsManySNPs=798242
+HsManyIndels=88694
+
+StaphOneSNPs=27000
+StaphOneIndels=3000
+StaphManySNPs=202081
+StaphManyIndels=22453
+
+all: $(PROFILE_READS) $(REFS) $(PROJ)
+
+clean:
+	rm -rf staph chr1 $(NAMES)
+
+test:
+	echo $(PROJ)
+
+$(PROFILE_READS):
+	@echo Please fetch $(PROFILE_READS) from Illumina or pass other with PROFILE_READS=
+	exit 1;
+
+$(PROJ): $(REFS)
 
 chr1/chr1.orig.fa.gz:
 	mkdir -p chr1
 	wget -O chr1/chr1.orig.fa.gz '$(HGCHR1)'
 
-staph/staph.orig.fa:
+staph/staph.orig.fa.gz:
 	mkdir -p staph
 	wget -O staph/staph.orig.fa '$(STAPH)'
+	gzip staph/staph.orig.fa
 
-chr1/chr1.fa.gz: chr1/chr1.orig.fa.gz
-	zcat chr1/chr1.orig.fa.gz | tr -d 'N' | $(FACAT) -w 50 > chr1/chr1.fa
-	gzip -c chr1/chr1.fa > chr1/chr1.fa.gz
-	samtools faidx chr1/chr1.fa
-	samtools faidx chr1/chr1.fa.gz
-	$(STAMPY) -G chr1/chr1 chr1/chr1.fa.gz
-	$(STAMPY) -g chr1/chr1 -H chr1/chr1
+%.fa: %.orig.fa.gz
+	zcat $< | tr -d 'N' | $(FACAT) -w 50 > $@
 
-staph/staph.fa.gz: staph/staph.orig.fa
-	cat staph/staph.orig.fa | tr -d 'N' | $(FACAT) -w 50 > staph/staph.fa
-	gzip -c staph/staph.fa > staph/staph.fa.gz
-	samtools faidx staph/staph.fa
-	samtools faidx staph/staph.fa.gz
-	$(STAMPY) -G staph/staph staph/staph.fa.gz
-	$(STAMPY) -g staph/staph -H staph/staph
+%.fa.gz: %.fa
+	gzip -c $< > $@
 
-# Number of events [hs][SI][OM]
-# h=human s=staph S=SNPs I=indels O=one M=many
-hSO=225000
-hSM=798242
-hIO=25000
-hIM=88694
+%.fa.fai: %.fa
+	samtools faidx $<
 
-sSO=27000
-sSM=202081
-sIO=3000
-SIM=22453
+#$* is {Hs,Staph}{One,Many}{Error,NoError}Reads{100,250}
+$(PROJ): proj%:
+	echo $*
+	proj=`echo $* | sed 's/^proj//g'`; \
+	species=`echo $* | grep -oE '(Hs|Staph)'`; \
+	quant=`echo $* | grep -oE '(One|Many)'`; \
+	err=`echo $* | grep -oE '(NoError|Error)'`; \
+	readlen=`echo $* | grep -oE '[0-9]*$$'`; \
+	errprof=; \
+	if [ $$species == 'Hs' ]; then \
+		ref=../chr1.fa; ploidy=2; allelecovg=30; \
+		if [ $$quant == 'Many' ]; then num=10; snps=$(HsManySNPs); indels=$(HsManyIndels); \
+		else num=1; snps=$(HsOneSNPs); indels=$(HsOneIndels); fi; \
+	else \
+		ref=../staph.fa; ploidy=1; allelecovg=100; \
+		if [ $$quant == 'Many' ]; then num=1000; snps=$(StaphManySNPs); indels=$(StaphManyIndels); \
+		else num=1; snps=$(StaphOneSNPs); indels=$(StaphOneIndels); fi; \
+	fi; \
+	if [ $$err == 'Error' ]; then errprof="ERRPROF=../$(PROFILE_READS)"; fi; \
+	mkdir -p $*; cd $*; \
+	echo make -f ../../calling-comparison.mk \
+					SEQ=$$ref NUM_INDIVS=$$num PLOIDY=$$ploidy KMER=31 \
+					SNPS=$$snps INDELS=$$indels INV=0 INVLEN=100 \
+					READLEN=$$readlen MPSIZE=250 ALLELECOVG=$$allelecovg $$errprof \
+					MEMWIDTH=20 MEMHEIGHT=20 >& $$proj/run.log
 
-run-files:
-	mkdir -p OneHumanErrorReads100   OneStaphErrorReads100   OneHumanErrorReads250   OneStaphErrorReads250
-	mkdir -p OneHumanNoErrorReads100 OneStaphNoErrorReads100 OneHumanNoErrorReads250 OneStaphNoErrorReads250
-	mkdir -p ManyHumanErrorReads100  ManyStaphErrorReads100  ManyHumanErrorReads250  ManyStaphErrorReads250
-	#
-	../run-sample-pop.sh ../chr1/chr1.fa  ../chr1/chr1    1 2 31 $(hSO) $(hIO) 0 0 100 250 30  ../PhiX.1.fq.gz print 24 24 > OneHumanErrorReads100/run.sh
-	../run-sample-pop.sh ../staph/staph.fa ../staph/staph 2 1 31 $(sSO) $(sIO) 0 0 100 250 100 ../PhiX.1.fq.gz print 24 24 > OneStaphErrorReads100/run.sh
-	../run-sample-pop.sh ../chr1/chr1.fa  ../chr1/chr1    1 2 31 $(hSO) $(hIO) 0 0 250 250 30  ../PhiX.1.fq.gz print 24 24 > OneHumanErrorReads250/run.sh
-	../run-sample-pop.sh ../staph/staph.fa ../staph/staph 2 1 31 $(sSO) $(sIO) 0 0 250 250 100 ../PhiX.1.fq.gz print 24 24 > OneStaphErrorReads250/run.sh
-	#
-	../run-sample-pop.sh ../chr1/chr1.fa  ../chr1/chr1    1 2 31 $(hSO) $(hSO) 0 0 100 250 30  noerror print 24 24 > OneHumanNoErrorReads100/run.sh
-	../run-sample-pop.sh ../staph/staph.fa ../staph/staph 2 1 31 $(sSO) $(sSO) 0 0 100 250 100 noerror print 24 24 > OneStaphNoErrorReads100/run.sh
-	../run-sample-pop.sh ../chr1/chr1.fa  ../chr1/chr1    1 2 31 $(hSO) $(hSO) 0 0 250 250 30  noerror print 24 24 > OneHumanNoErrorReads250/run.sh
-	../run-sample-pop.sh ../staph/staph.fa ../staph/staph 2 1 31 $(sSO) $(sSO) 0 0 250 250 100 noerror print 24 24 > OneStaphNoErrorReads250/run.sh
-	#
-	../run-sample-pop.sh ../chr1/chr1.fa  ../chr1/chr1    10   2 31 $(hSM) $(hSM) 0 0 100 250 30  ../PhiX.1.fq.gz print 24 24 > ManyHumanErrorReads100/run.sh
-	../run-sample-pop.sh ../staph/staph.fa ../staph/staph 1000 1 31 $(sSM) $(sSM) 0 0 100 250 100 ../PhiX.1.fq.gz print 24 24 > ManyStaphErrorReads100/run.sh
-	../run-sample-pop.sh ../chr1/chr1.fa  ../chr1/chr1    10   2 31 $(hSM) $(hSM) 0 0 250 250 30  ../PhiX.1.fq.gz print 24 24 > ManyHumanErrorReads250/run.sh
-	../run-sample-pop.sh ../staph/staph.fa ../staph/staph 1000 1 31 $(sSM) $(sSM) 0 0 250 250 100 ../PhiX.1.fq.gz print 24 24 > ManyStaphErrorReads250/run.sh
-
-clean:
-	rm -rf staph.fa* chr1.fa* staph.st* chr1.st*
-
-.PHONY: all clean run-files
+.PHONY: all clean test $(PROJ)
